---
- name: a play that upgrades a VyOS device
  hosts: vyos
  gather_facts: false
  vars:
    sysimg_url: https://downloads.vyos.io/rolling/current/amd64/vyos-rolling-latest.iso

  tasks:
  - name: abort unless target host has ansible_network_os == 'vyos'
    assert:
      that: "ansible_network_os == 'vyos'"

  - name: get old system image information
    vyos_command:
      commands:
      - show system image
    register: old_system_image

  - name: show old system image information
    debug:
      msg: "{{ old_system_image.stdout }}"

  - name: download the new image first on the disk.
    get_url:
      url: https://downloads.vyos.io/rolling/current/amd64/vyos-rolling-latest.iso
      dest: /home/vyos/vyos-rolling-latest.iso
 
  - name: Installing the new image from the filesystem (mandatory check for all prompts)
    cli_command:
      command: "add system image vyos-rolling-latest.iso"
      check_all: True
      prompt: 
        - What would you like to name this image?
        - "Yes"
        - "Yes"
      answer:
        - ' '
        - 'Yes'
        - 'Yes'
    register: vardownload

  - name: show new system image information
    debug:
      msg: "{{ vardownload }}"
  
  - name: get new system image information
    vyos_command:
      commands:
      - show system image
    register: new_system_image
    

  - name: show new system image information
    debug:
      msg: "{{ new_system_image.stdout }}"
  
  - name: keeping the same image as default
    cli_command:
      command: set system image default-boot 1.3-rolling-202005280117

